#!/bin/bash
# Xcode Cloud post-clone script
# Xcode Cloud resolves SPM dependencies automatically.
# This script is intentionally minimal to avoid timeout issues.
set -e

# Materialise private identifiers for the build: the public repo carries
# placeholders in Config/Base.xcconfig; Xcode Cloud provides the real values
# as workflow environment variables, written here into the git-ignored
# Config/Local.xcconfig (same mechanism as a local developer checkout).
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
if [ -n "${BRAIN_BUNDLE_ID_BASE:-}" ]; then
    {
        echo "// Generated by ci_post_clone.sh from Xcode Cloud environment variables."
        echo "BRAIN_BUNDLE_ID_BASE = ${BRAIN_BUNDLE_ID_BASE}"
        if [ -n "${BRAIN_TEAM_ID:-}" ]; then
            echo "BRAIN_TEAM_ID = ${BRAIN_TEAM_ID}"
        fi
        if [ -n "${BRAIN_GOOGLE_CLIENT_ID:-}" ]; then
            echo "BRAIN_GOOGLE_CLIENT_ID = ${BRAIN_GOOGLE_CLIENT_ID}"
        fi
    } > "$REPO_ROOT/Config/Local.xcconfig"
    echo "Post-clone: Config/Local.xcconfig written from environment (bundle id base: ${BRAIN_BUNDLE_ID_BASE})."
else
    echo "Post-clone: BRAIN_BUNDLE_ID_BASE not set — building with placeholder identifiers."
fi

# Skip build if only documentation files changed (saves Xcode Cloud minutes)
if [ -n "$CI_PULL_REQUEST_NUMBER" ] || [ -z "$CI_COMMIT" ]; then
    echo "Post-clone: PR build or no commit info — proceeding with build."
else
    # Xcode Cloud may use shallow clones — git diff can fail with exit 128
    # if the parent commit object is not available. Handle gracefully.
    PREV_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo "")
    if [ -n "$PREV_COMMIT" ]; then
        CHANGED_FILES=$(git diff --name-only "$PREV_COMMIT" HEAD 2>/dev/null || echo "")
        if [ -z "$CHANGED_FILES" ]; then
            echo "Post-clone: Could not determine changed files (shallow clone?) — proceeding with build."
        else
            CODE_CHANGES=$(echo "$CHANGED_FILES" | grep -v -E '\.(md|txt)$' | grep -v -E '^docs/' | grep -v -E '^\.claude/' || true)
            if [ -z "$CODE_CHANGES" ]; then
                echo "Post-clone: Only documentation changed — skipping build."
                echo "Changed files: $CHANGED_FILES"
                exit 1
            fi
        fi
    fi
fi

echo "Post-clone: Code changes detected — proceeding with build."
